export const FETCH_CITY_START = "FETCH_CITY_START";
export const FETCH_CITY_SUCCESS = "FETCH_CITY_SUCCESS";
export const FETCH_CITY_FAILURE = " FETCH_CITY_FAILURE";
export const ADD_CITY = "ADD_CITY";
export const ADD_RESTAURANT = "ADD_RESTAURANT";
